import React from "react";
import ColorWheelColor from "components/ColorWheelColor";
import styled from "styled-components";

const Wrapper = styled.div`
  margin-top: 10px;
`;

const ColorWheelLine = styled.div`
  display: flex;
  justify-content: center;
  margin-top: -7px;
`;

const ColorWheel = props => {
  const { selectColor, colorType, activeColor } = props;
  return (
    <Wrapper>
      <ColorWheelLine>
        <ColorWheelColor
          color="#003366"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#336699"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#3366cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#003399"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#000099"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0000cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#000066"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#006666"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#006699"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0099cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0066cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0033cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0000ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#3333ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#333399"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#669999"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#009999"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#33cccc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00ccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0099ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#0066ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#3366ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#3333cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#666699"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#339966"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00cc99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00ffcc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00ffff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#33ccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#3399ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#6699ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#6666ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#6600ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#6600cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#339933"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00cc66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00ff99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ffcc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ffff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99ccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#9999ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#9966ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#9933ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#9900ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#006600"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00cc00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#00ff00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ff99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99ffcc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccffff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc99ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc66ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc33ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc00ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#9900cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#003300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#009933"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#33cc33"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ff66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99ff99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccffcc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffffff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffccff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff99ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff66ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff00ff"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc00cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#660066"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#336600"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#009900"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#66ff33"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99ff66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccff99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffffcc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffcccc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff99cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff66cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff33cc"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc0099"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#993399"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#333300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#669900"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99ff33"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccff66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffff99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffcc99"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff9999"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff6699"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff3399"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc3399"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#990099"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#666633"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#99cc00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ccff33"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffff66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffcc66"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff9966"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff6666"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff0066"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc6699"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#993366"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#999966"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cccc00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffff00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ffcc00"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff9933"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff6600"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff5050"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc0066"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#660033"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#996633"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc9900"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff9900"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc6600"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff3300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#ff0000"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc0000"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#990033"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
      <ColorWheelLine>
        <ColorWheelColor
          color="#663300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#996600"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#cc3300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#993300"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#990000"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#800000"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
        <ColorWheelColor
          color="#993333"
          selectColor={selectColor}
          colorType={colorType}
          activeColor={activeColor}
        />
      </ColorWheelLine>
    </Wrapper>
  );
};

export default ColorWheel;
